### ISSUE TITLE
Adding numlock.key results to globalkeys gives error

### ISSUE THREAD

**Issue by MrHappy** [iacchus/awesomewm-numlock-widget#1]
The plugin starts fine with AweSome (it is in the topbar), it just won't update when I hit numlock.

It gives the error
`attempt to index a nil value (global numlock)`

Removing 'numlock.key' prevents the error from showing, but also prevents update the topbar.

How can I find out what is wrong?

**Comment by iacchus** [comment]
Hello! you did the three steps in the readme, right?

I think you skipped the first step, and possibly the second also.

## First, add somewhere early in your `rc.lua`:
only the first line is important; the others are for setting it up the preferred manner

```lua
local numlock = require("awesomewm-numlock-widget")
numlock.forced_width = 35
numlock.activated = "<b><span font_family='monospace' foreground='#ffffff' background='#669966'> num </span></b>"
numlock.deactivated = "<span font_family='monospace'> num </span>"
```

you can add it before:

```lua
terminal = -- etc etc etc line
```

## Secondly, add the widget to the wibox:
Look for `-- Right widgets`, as shown below, and add the line `numlock,` where you want to see the widget (pay attention to the ending commas `,`):

```lua
s.mywibox:setup {

    -- more config here...

    { -- Right widgets
        layout = wibox.layout.fixed.horizontal,
        wibox.widget.systray(),
        numlock,
        -- more config here
```

## Third; add the keybinding to `global_keys` so that the widget can change state on keypress, by adding the line `numlock.key` there:

```lua
-- {{{ Key bindings
local globalkeys = awful.util.table.join(
  numlock.key,
-- more config follows
```
## It should work; if still not, please check the output of command: `bash -c 'sleep 0.2 && xset q'`

This command is executed by the script, [in line 61](https://github.com/iacchus/awesomewm-numlock-widget/blob/66f7e2b908bd4663c7cc1660486da30881cdb1fa/init.lua#L61)

It's output should be like this (showing current `Num lock` status):

![Screenshot from 2022-03-03 16-57-11](https://user-images.githubusercontent.com/881531/156642334-9f78ab47-a27c-4274-a23e-7577a43bb1b3.png)

Please tell me if this solves it... :)

**Comment by MrHappy** [comment]
Thanks for your elaborate response ;)
I have the line `local numlock = require('widget.numlock')` in top-panel.lua, where the widget is added also.

Top-panel.lua is called from layout/init.lua by `local top_panel = require('layout.top-panel')`.
And layout.init is called wit `require('layout')` from rc.lua.

When I add the keybinding to global_keys I get the error `attempt to index a nil value (global numlock)`.

So I followed the steps, al be it in different files than you said. (Btw. I used the dotfiles for Awesome of ChrisTitus, maybe that helps?)

The widget is show with the status of numlock which it had when Awesome started.
If I turn off numlock and restart Awesome it shows the status off.

--Edit:
found it...
I had to add
`local capslock = require('widget.capslock')
local numlock = require('widget.numlock')
local scrolllock = require('widget.scrolllock')`
in (my) `configuration/keys/global.lua` also. Now it works!

Thanks!
